#!/bin/sh
NAME="nam"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ln -s $DIR/$NAME ~/bin/$NAME > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
    echo "Symlink '$NAME' added to ~/bin/"
else
    echo "Nothing to do : Already installed"
fi
